---
- name: "Task 2 & 3: Infrastructure Setup and App Deployment"
  hosts: nodes
  become: yes
  tasks:
    - name: "1. Перевірка вільного місця (Pre-check)"
      shell: df -h / | tail -1 | awk '{print $4}' | sed 's/G//'
      register: disk_free
      failed_when: disk_free.stdout | float < 2.0

    - name: "2. Оновлення системних пакетів"
      apt:
        update_cache: yes
        name: [apt-transport-https, ca-certificates, curl, software-properties-common, conntrack]

    - name: "3. Встановлення Docker"
      apt:
        name: docker.io
        state: present

    - name: "4. Встановлення kubectl"
      get_url:
        url: "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: "5. Встановлення Minikube"
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: "6. Встановлення Helm"
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: "7. Запуск Minikube"
      become: no
      command: minikube start --driver=docker
      register: minikube_start
      changed_when: "'Done!' in minikube_start.stdout"

    - name: "8. Запуск kubectl proxy (Requirement: Proxy access)"
      become: no
      shell: "nohup kubectl proxy --port=8001 --address='0.0.0.0' --accept-hosts='.*' > /dev/null 2>&1 &"
      async: 10
      poll: 0

    - name: "9. Очищення старих релізів Helm (якщо були)"
      become: no
      command: helm uninstall dev-app release-app
      ignore_errors: yes
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: "10. Деплой DEV середовища (Port 8002)"
      become: no
      command: >
        helm upgrade --install dev-app ../task3 
        --set image.tag=develop 
        --set service.nodePort=8002 
        --set image.repository={{ lookup('env', 'DOCKERHUB_USERNAME') }}/exam-app
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: "11. Деплой RELEASE середовища (Port 8003)"
      become: no
      command: >
        helm upgrade --install release-app ../task3 
        --set image.tag=1.0.0 
        --set service.nodePort=8003
        --set image.repository={{ lookup('env', 'DOCKERHUB_USERNAME') }}/exam-app
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: "12. Перевірка запущених подів"
      become: no
      command: kubectl get pods
      register: pods_status
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: "13. Вивід фінального статусу"
      debug:
        msg: "{{ pods_status.stdout }}"
