---
- name: "Task 2 & 3: Infrastructure Setup and App Deployment"
  hosts: all
  become: no
  tasks:
    - name: "1. Системні пакети"
      apt:
        update_cache: yes
        name: [apt-transport-https, ca-certificates, curl, software-properties-common, git, wget]

    - name: "2. Встановлення K3s (Легкий Kubernetes)"
      shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--write-kubeconfig-mode 644' sh -"
      args:
        creates: /usr/local/bin/k3s

    - name: "3. Встановлення Helm"
      shell: "curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
      args:
        creates: /usr/local/bin/helm

    - name: "4. Створення посилань для сумісності"
      shell: |
        mkdir -p /root/.kube
        cp /etc/rancher/k3s/k3s.yaml /root/.kube/config
      ignore_errors: yes

    - name: "5. Деплой додатків через Helm"
      shell: |
        helm upgrade --install dev-app ../task3 \
          --set image.tag=develop \
          --set service.type=NodePort \
          --set service.nodePort=30002 \
          --set image.repository={{ lookup('env', 'DOCKERHUB_USERNAME') }}/exam-app
          
        helm upgrade --install release-app ../task3 \
          --set image.tag=1.0.0 \
          --set service.type=NodePort \
          --set service.nodePort=30003 \
          --set image.repository={{ lookup('env', 'DOCKERHUB_USERNAME') }}/exam-app
      environment:
        KUBECONFIG: /root/.kube/config

    - name: "6. Перевірка"
      command: kubectl get pods
      register: pods_status
      environment:
        KUBECONFIG: /root/.kube/config

    - name: "7. Результат"
      debug:
        msg: "{{ pods_status.stdout }}"
