name: "Ansible Deployment"

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Terraform Infrastructure"]
    types:
      - completed

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Run Ansible Playbook"
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: setup.yml
          directory: task2
          inventory: inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --extra-vars "ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
