name: "Terraform Infrastructure"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Build"
    runs-on: ubuntu-latest
    
    env:
      # Ключі для доступу до бакета (Backend S3)
      AWS_ACCESS_KEY_ID: ${{ secrets.DIGITALOCEAN_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DIGITALOCEAN_SECRET_KEY }}
      
      # Змінні для провайдера DigitalOcean
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_spaces_access_id: ${{ secrets.DIGITALOCEAN_ACCESS_KEY }}
      TF_VAR_spaces_secret_key: ${{ secrets.DIGITALOCEAN_SECRET_KEY }}
      
      # ОСЬ ЦЕЙ РЯДОК ПРИБЕРЕ ЗАВИСАННЯ НА 9 ХВИЛИН:
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: "Terraform Init"
        run: |
          cd task1
          terraform init \
            -backend-config="access_key=${{ env.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}"

      - name: "Terraform Plan"
        run: |
          cd task1
          terraform plan -no-color

      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: |
          cd task1
          terraform apply -auto-approve
