name: "Terraform Infrastructure"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Build"
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DIGITALOCEAN_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DIGITALOCEAN_SECRET_KEY }}
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: |
          cd task1
          terraform init \
            -backend-config="access_key=${{ env.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}"

      - name: "Terraform Plan"
        run: cd task1 && terraform plan

      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: cd task1 && terraform apply -auto-approve
